apiVersion: v1
kind: ConfigMap
metadata:
  name: my-validator
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-functions/validate-rolebinding
    config.kubernetes.io/local-config: "true"
data:
  subject_name: bad_actor
