apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: full-admin
  namespace: default
subjects:
- kind: User
  name: bad_actor
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
